spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:23307/moms?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: moms1234
  jackson:
#    date-format: yyyyMMdd
    serialization:
      write-dates-as-timestamps: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  forward-headers-strategy: FRAMEWORK

api:
  version: v1
  description: Momsitter api

jwt:
  secret: "bW9tc2l0dGVyLWFwaS1yZWN1aXJ0LXRlc3Qtand0LXNlcmNldC1jb2Rl"
  access-token-expireTime: 600000 #10minute
  refresh-token-expireTime: 7776000000 #90days